import {
  atbashTransform,
  caesarEncrypt,
  CHARSET_PRESETS,
  normalizeShift,
  validateCharset,
} from '../lib/crypto/index.js';

export const SPANISH_PHRASES = Object.freeze([
  'LA SEGURIDAD DIGITAL REQUIERE ATENCION CONSTANTE Y DECISIONES RESPONSABLES.',
  'EL ANALISIS DE FRECUENCIAS PERMITE COMPARAR PATRONES DEL LENGUAJE ESCRITO.',
  'CADA MENSAJE CONTIENE PISTAS SOBRE LAS PALABRAS Y LA ESTRUCTURA DEL IDIOMA.',
  'UN BUEN PROGRAMA DEBE VALIDAR SUS ENTRADAS ANTES DE PROCESAR LA INFORMACION.',
  'LA CRIPTOGRAFIA CLASICA AYUDA A COMPRENDER LA HISTORIA DE LA SEGURIDAD.',
  'ESTE PROYECTO FUNCIONA DE MANERA LOCAL DENTRO DEL NAVEGADOR WEB.',
  'LOS DATOS PERSONALES NUNCA DEBEN PROTEGERSE MEDIANTE UN CIFRADO ANTIGUO.',
  'MAÑANA PRESENTAREMOS EL SISTEMA ANTE EL GRUPO Y EXPLICAREMOS SUS LIMITACIONES.',
  '¿COMO PUEDE EL PROGRAMA ENCONTRAR LA FRASE CORRECTA SIN AYUDA HUMANA?',
  '¡EL RESULTADO MAS PROBABLE APARECE DESPUES DE EVALUAR TODOS LOS CANDIDATOS!',
  'DURANTE LA PRUEBA OBSERVAMOS QUE LOS SIGNOS, ESPACIOS Y NUMEROS 2026 PERMANECEN.',
  'LAS PALABRAS COMUNES APORTAN EVIDENCIA, PERO NO SON LA UNICA SEÑAL UTIL.',
  'UNA DISTRIBUCION RAZONABLE DE VOCALES SUELE DISTINGUIR EL ESPAÑOL DEL RUIDO.',
  'EL EQUIPO REVISA EL CODIGO PARA EVITAR ERRORES Y REDUCIR RIESGOS INNECESARIOS.',
  'NINGUN ALGORITMO CLASICO DEBE CONFUNDIRSE CON PROTECCION CRIPTOGRAFICA MODERNA.',
  'LA UNIVERSIDAD PROMUEVE EL PENSAMIENTO CRITICO Y EL APRENDIZAJE RESPONSABLE.',
  'CUANDO TERMINA EL ANALISIS, LA APLICACION MUESTRA SOLAMENTE UNA RESPUESTA.',
  'EL DESPLAZAMIENTO SE NORMALIZA SEGUN EL TAMAÑO REAL DEL CONJUNTO ELEGIDO.',
  'ATBASH INVIERTE EL ORDEN DE LOS CARACTERES Y CONSERVA LOS SIMBOLOS EXTERNOS.',
  'CESAR RECORRE CADA POSICION MEDIANTE UNA OPERACION MODULAR REVERSIBLE.',
  'LA CIENCIA AVANZA CUANDO LAS IDEAS PUEDEN MEDIRSE, PROBARSE Y CORREGIRSE.',
  'HOY LLUEVE EN LA CIUDAD, PERO EL LABORATORIO CONTINUA ABIERTO.',
  'MI HERMANA LEE UN LIBRO MIENTRAS ESCUCHA MUSICA EN LA SALA.',
  'LOS ESTUDIANTES PREPARAN PREGUNTAS PARA LA CLASE DEL PROXIMO LUNES.',
  'UNA CONTRASEÑA LARGA Y UNICA NECESITA UN GESTOR SEGURO, NO CESAR.',
  'EL SERVIDOR PUBLICO DEBE USAR HTTPS Y UNA POLITICA DE CONTENIDO RESTRICTIVA.',
  'PROBAR CASOS EXTRAÑOS REVELA SUPOSICIONES QUE EL DISEÑO NO HABIA CONSIDERADO.',
  'EL MENSAJE FINAL CONSERVA COMAS, PUNTOS, DOS PUNTOS Y SIGNOS DE PREGUNTA.',
  'NUESTRO OBJETIVO ES ENTENDER EL METODO Y DOCUMENTAR SUS LIMITES CON CLARIDAD.',
  'LA CLAVE ES CORRECTA Y EL TEXTO VUELVE A SER LEGIBLE.',
  'EN POCOS MINUTOS PODEMOS CIFRAR, COPIAR, ANALIZAR Y EXPLICAR EL RESULTADO.',
  'AL KINDI ESTUDIO LA FRECUENCIA DE LAS LETRAS PARA ROMPER SUSTITUCIONES SIMPLES.',
]);

export const ALPHANUMERIC_PHRASES = Object.freeze([
  'EL INFORME 2026 CONTIENE 12 PRUEBAS IMPORTANTES Y 3 RESULTADOS PRINCIPALES.',
  'LA VERSION 2 DEL PROGRAMA ANALIZA 37 CARACTERES EN CADA DESPLAZAMIENTO.',
  'HOY REVISAMOS 5 MODULOS DE CODIGO Y CORREGIMOS 2 ERRORES DE VALIDACION.',
  'EL EQUIPO A PRESENTA EL CASO 18 DURANTE LA CLASE DE SEGURIDAD.',
  'UNA CLAVE DE PRUEBA 12345 NO DEBE USARSE PARA PROTEGER DATOS REALES.',
  'LA DEMOSTRACION TARDA 4 MINUTOS Y UTILIZA 6 EJEMPLOS REPRODUCIBLES.',
]);

const DEFAULT_SHIFTS = [1, 2, 5, 9, 14, 26];
const LOWERCASE_SHIFTS = [3, 11, 20];
const ALPHANUMERIC_SHIFTS = [4, 13, 25, 36];

function buildCases(phrases, charset, shifts, prefix) {
  const characters = validateCharset(charset).characters;
  const cases = [];

  phrases.forEach((plaintext, phraseIndex) => {
    for (const shift of shifts) {
      cases.push({
        id: `${prefix}-caesar-${phraseIndex + 1}-s${shift}`,
        algorithm: 'caesar',
        charset,
        shift: normalizeShift(shift, characters.length),
        plaintext,
        ciphertext: caesarEncrypt(plaintext, characters, shift),
      });
    }

    cases.push({
      id: `${prefix}-atbash-${phraseIndex + 1}`,
      algorithm: 'atbash',
      charset,
      shift: null,
      plaintext,
      ciphertext: atbashTransform(plaintext, characters),
    });
  });

  return cases;
}

const lowercasePhrases = SPANISH_PHRASES.slice(0, 10).map((phrase) => phrase.toLocaleLowerCase('es'));

export const DETECTION_CASES = Object.freeze([
  ...buildCases(SPANISH_PHRASES, CHARSET_PRESETS.spanish, DEFAULT_SHIFTS, 'es'),
  ...buildCases(lowercasePhrases, CHARSET_PRESETS.lowercase, LOWERCASE_SHIFTS, 'lower'),
  ...buildCases(ALPHANUMERIC_PHRASES, CHARSET_PRESETS.alphanumeric, ALPHANUMERIC_SHIFTS, 'alnum'),
]);
